[project]
name = "kv-caching"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "huggingface-hub>=1.23.0",
    "pandas>=3.0.3",
    "pyarrow>=25.0.0",
    "tensorboard>=2.21.0",
    "tensorboard-plugin-profile>=2.23.1",
    "tokenizers>=0.23.1",
    "torch>=2.13.0",
    "tqdm>=4.68.4",
]
